// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpeo6S9jfEv5W1qIkSsaX8IaUuRL8f6Q',
    appId: '1:615627257945:web:051e9963b1ca64e1b81948',
    messagingSenderId: '615627257945',
    projectId: 'choicex-8590',
    authDomain: 'choicex-8590.firebaseapp.com',
    storageBucket: 'choicex-8590.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzi5TTiTsjewlElgWIY27v9Y5so5zDluk',
    appId: '1:615627257945:android:e3c3785bdcf8d557b81948',
    messagingSenderId: '615627257945',
    projectId: 'choicex-8590',
    storageBucket: 'choicex-8590.firebasestorage.app',
   
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4_bxdRP2j6HvQ_PJbZGmhwvt7WN5OLHI',
    appId: '1:615627257945:ios:48ac4f81f236af2cb81948',
    messagingSenderId: '615627257945',
    projectId: 'choicex-8590',
    storageBucket: 'choicex-8590.firebasestorage.app',
    iosBundleId: 'com.example.coice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKpeo6S9jfEv5W1qIkSsaX8IaUuRL8f6Q',
    appId: '1:615627257945:web:fd614b7ef4f19b34b81948',
    messagingSenderId: '615627257945',
    projectId: 'choicex-8590',
    authDomain: 'choicex-8590.firebaseapp.com',
    storageBucket: 'choicex-8590.firebasestorage.app',
  );
}
